### ISSUE TITLE
Output folder for .PARAFFIN file

### ISSUE THREAD

**Issue by lilphil** [Wintellect/Paraffin#22]
Hi,
We're just getting into using paraffin, looks good! It would be great if it was possible to specify the output path for the resulting file during -update though, or am I missing something?

**Comment by JohnWintellect** [comment]
Thanks for using Paraffin! There's not a way to specify a different output path. The .wxs file needs to be in the same place where it was created in order to know where to find the rest of the files. It would have made the code massively more complicated to handle divergent directories. Hope it helps.
